//
//  ContentData.swift
//  KidsLearnApp
//
//  Created by Uday Kumar on 11/03/2026.
//

import Foundation

enum ContentData {
    
    static func letters(for lang: AppLanguage) -> [LetterItem] {
        switch lang {
        case .english:
            return [
                .init(symbol: "A", exampleWord: "Apple", exampleEmoji: "🍎",
                      gifName: "A_apple", audioName: "en_A"),
                .init(symbol: "B", exampleWord: "Ball", exampleEmoji: "🏀",
                      gifName: "B_ball", audioName: "en_B"),
                .init(symbol: "C", exampleWord: "Cat", exampleEmoji: "🐱",
                      gifName: "C_cat", audioName: "en_C"),
                .init(symbol: "D", exampleWord: "Dog", exampleEmoji: "🐶",
                      gifName: "D_dog", audioName: "en_D"),
                .init(symbol: "E", exampleWord: "Elephant", exampleEmoji: "🐘",
                      gifName: "E_elephant", audioName: "en_E"),
                .init(symbol: "F", exampleWord: "Fish", exampleEmoji: "🐟",
                      gifName: "F_fish", audioName: "en_F"),
                .init(symbol: "G", exampleWord: "Goat", exampleEmoji: "🐐",
                      gifName: "G_goat", audioName: "en_G"),
                .init(symbol: "H", exampleWord: "House", exampleEmoji: "🏠",
                      gifName: "H_house", audioName: "en_H"),
                .init(symbol: "I", exampleWord: "Ice cream", exampleEmoji: "🍦",
                      gifName: "I_icecream", audioName: "en_I"),
                .init(symbol: "J", exampleWord: "Juice", exampleEmoji: "🧃",
                      gifName: "J_juice", audioName: "en_J"),
                .init(symbol: "K", exampleWord: "Kite", exampleEmoji: "🪁",
                      gifName: "K_kite", audioName: "en_K"),
                .init(symbol: "L", exampleWord: "Lion", exampleEmoji: "🦁",
                      gifName: "L_lion", audioName: "en_L"),
                .init(symbol: "M", exampleWord: "Monkey", exampleEmoji: "🐒",
                      gifName: "M_monkey", audioName: "en_M"),
                .init(symbol: "N", exampleWord: "Nest", exampleEmoji: "🪺",
                      gifName: "N_nest", audioName: "en_N"),
                .init(symbol: "O", exampleWord: "Orange", exampleEmoji: "🍊",
                      gifName: "O_orange", audioName: "en_O"),
                .init(symbol: "P", exampleWord: "Parrot", exampleEmoji: "🦜",
                      gifName: "P_parrot", audioName: "en_P"),
                .init(symbol: "Q", exampleWord: "Queen", exampleEmoji: "👑",
                      gifName: "Q_queen", audioName: "en_Q"),
                .init(symbol: "R", exampleWord: "Rabbit", exampleEmoji: "🐰",
                      gifName: "R_rabbit", audioName: "en_R"),
                .init(symbol: "S", exampleWord: "Sun", exampleEmoji: "☀️",
                      gifName: "S_sun", audioName: "en_S"),
                .init(symbol: "T", exampleWord: "Tiger", exampleEmoji: "🐯",
                      gifName: "T_tiger", audioName: "en_T"),
                .init(symbol: "U", exampleWord: "Umbrella", exampleEmoji: "☂️",
                      gifName: "U_umbrella", audioName: "en_U"),
                .init(symbol: "V", exampleWord: "Van", exampleEmoji: "🚐",
                      gifName: "V_van", audioName: "en_V"),
                .init(symbol: "W", exampleWord: "Wolf", exampleEmoji: "🐺",
                      gifName: "W_wolf", audioName: "en_W"),
                .init(symbol: "X", exampleWord: "Xylophone", exampleEmoji: "🎼",
                      gifName: "X_xylophone", audioName: "en_X"),
                .init(symbol: "Y", exampleWord: "Yak", exampleEmoji: "🐃",
                      gifName: "Y_yak", audioName: "en_Y"),
                .init(symbol: "Z", exampleWord: "Zebra", exampleEmoji: "🦓",
                      gifName: "Z_zebra", audioName: "en_Z")
            ]
            
        case .telugu:
            return [
                // Vowels (Acchulu)
                .init(symbol: "అ", exampleWord: "అమ్మ", exampleEmoji: "👩‍👧",
                      gifName: "telugu_a_amma", audioName: "te_అ"),
                .init(symbol: "ఆ", exampleWord: "ఆవు", exampleEmoji: "🐄",
                      gifName: "telugu_aa_aavu", audioName: "te_ఆ"),
                .init(symbol: "ఇ", exampleWord: "ఇల్లు", exampleEmoji: "🏠",
                      gifName: "telugu_i_illu", audioName: "te_ఇ"),
                .init(symbol: "ఈ", exampleWord: "ఈగ", exampleEmoji: "🪰",
                      gifName: "telugu_ee_eega", audioName: "te_ఈ"),
                .init(symbol: "ఉ", exampleWord: "ఉడుత", exampleEmoji: "🐿️",
                      gifName: "telugu_u_udutha", audioName: "te_ఉ"),
                .init(symbol: "ఊ", exampleWord: "ఊయల", exampleEmoji: "🪢",
                      gifName: "telugu_oo_uyala", audioName: "te_ఊ"),
                .init(symbol: "ఋ", exampleWord: "ఋషి", exampleEmoji: "🧘",
                      gifName: "telugu_ru_rushi", audioName: "te_ఋ"),
                .init(symbol: "ౠ", exampleWord: "ౠతువు", exampleEmoji: "📅",
                      gifName: "telugu_ruu_ruthuvu", audioName: "te_ౠ"),
                .init(symbol: "ఎ", exampleWord: "ఎలుక", exampleEmoji: "🐭",
                      gifName: "telugu_e_eluka", audioName: "te_ఎ"),
                .init(symbol: "ఏ", exampleWord: "ఏనుగు", exampleEmoji: "🐘",
                      gifName: "telugu_ee_enugu", audioName: "te_ఏ"),
                .init(symbol: "ఐ", exampleWord: "ఐరావతం", exampleEmoji: "🐘",
                      gifName: "telugu_ai_airavatham", audioName: "te_ఐ"),
                .init(symbol: "ఒ", exampleWord: "ఒంటె", exampleEmoji: "🐫",
                      gifName: "telugu_o_onte", audioName: "te_ఒ"),
                .init(symbol: "ఓ", exampleWord: "ఓడ", exampleEmoji: "🚢",
                      gifName: "telugu_oo_oda", audioName: "te_ఓ"),
                .init(symbol: "ఔ", exampleWord: "ఔషధం", exampleEmoji: "💊",
                      gifName: "telugu_au_aushadam", audioName: "te_ఔ"),
                .init(symbol: "అం", exampleWord: "అంబలి", exampleEmoji: "🥣",
                      gifName: "telugu_am_ambali", audioName: "te_అం"),
                .init(symbol: "అః", exampleWord: "అఃకారం", exampleEmoji: "😤",
                      gifName: "telugu_aha_ahakaram", audioName: "te_అః"),
                
                // Consonants (Hallulu)
                .init(symbol: "క", exampleWord: "కాకి", exampleEmoji: "🐦",
                      gifName: "telugu_ka_kaki", audioName: "te_క"),
                .init(symbol: "ఖ", exampleWord: "ఖడ్గం", exampleEmoji: "⚔️",
                      gifName: "telugu_kha_khadgam", audioName: "te_ఖ"),
                .init(symbol: "గ", exampleWord: "గజం", exampleEmoji: "🐘",
                      gifName: "telugu_ga_gajam", audioName: "te_గ"),
                .init(symbol: "ఘ", exampleWord: "ఘటం", exampleEmoji: "🏺",
                      gifName: "telugu_gha_ghatam", audioName: "te_ఘ"),
                .init(symbol: "ఙ", exampleWord: "ఙకారం", exampleEmoji: "🔤",
                      gifName: "telugu_nga_ngakaram", audioName: "te_ఙ"),
                .init(symbol: "చ", exampleWord: "చేప", exampleEmoji: "🐟",
                      gifName: "telugu_cha_chepa", audioName: "te_చ"),
                .init(symbol: "ఛ", exampleWord: "ఛత్రం", exampleEmoji: "☂️",
                      gifName: "telugu_chha_chatram", audioName: "te_ఛ"),
                .init(symbol: "జ", exampleWord: "జంతువు", exampleEmoji: "🐾",
                      gifName: "telugu_ja_janthuvu", audioName: "te_జ"),
                .init(symbol: "ఝ", exampleWord: "ఝరి", exampleEmoji: "💧",
                      gifName: "telugu_jha_jhari", audioName: "te_ఝ"),
                .init(symbol: "ఞ", exampleWord: "ఞకారం", exampleEmoji: "🔤",
                      gifName: "telugu_nya_nyakaram", audioName: "te_ఞ"),
                .init(symbol: "ట", exampleWord: "టమాట", exampleEmoji: "🍅",
                      gifName: "telugu_ta_tamata", audioName: "te_ట"),
                .init(symbol: "ఠ", exampleWord: "ఠీవి", exampleEmoji: "👑",
                      gifName: "telugu_tha_thiivi", audioName: "te_ఠ"),
                .init(symbol: "డ", exampleWord: "డమరుకం", exampleEmoji: "🥁",
                      gifName: "telugu_da_damarukam", audioName: "te_డ"),
                .init(symbol: "ఢ", exampleWord: "ఢంకా", exampleEmoji: "🥁",
                      gifName: "telugu_dha_dhanka", audioName: "te_ఢ"),
                .init(symbol: "ణ", exampleWord: "ణగణం", exampleEmoji: "🔔",
                      gifName: "telugu_na_naganam", audioName: "te_ణ"),
                .init(symbol: "త", exampleWord: "తాబేలు", exampleEmoji: "🐢",
                      gifName: "telugu_tha_thabelu", audioName: "te_త"),
                .init(symbol: "థ", exampleWord: "థాళం", exampleEmoji: "🥘",
                      gifName: "telugu_tha_thalamm", audioName: "te_థ"),
                .init(symbol: "ద", exampleWord: "దంతం", exampleEmoji: "🦷",
                      gifName: "telugu_dha_dantham", audioName: "te_ద"),
                .init(symbol: "ధ", exampleWord: "ధనువు", exampleEmoji: "🏹",
                      gifName: "telugu_dha_dhanuvu", audioName: "te_ధ"),
                .init(symbol: "న", exampleWord: "నక్క", exampleEmoji: "🦊",
                      gifName: "telugu_na_nakka", audioName: "te_న"),
                .init(symbol: "ప", exampleWord: "పిల్లి", exampleEmoji: "🐱",
                      gifName: "telugu_pa_pilli", audioName: "te_ప"),
                .init(symbol: "ఫ", exampleWord: "ఫలం", exampleEmoji: "🍎",
                      gifName: "telugu_pha_phalam", audioName: "te_ఫ"),
                .init(symbol: "బ", exampleWord: "బాతు", exampleEmoji: "🦆",
                      gifName: "telugu_ba_bathu", audioName: "te_బ"),
                .init(symbol: "భ", exampleWord: "భల్లూకం", exampleEmoji: "🐻",
                      gifName: "telugu_bha_bhallukam", audioName: "te_భ"),
                .init(symbol: "మ", exampleWord: "మయూరం", exampleEmoji: "🦚",
                      gifName: "telugu_ma_mayuram", audioName: "te_మ"),
                .init(symbol: "య", exampleWord: "యానకం", exampleEmoji: "✈️",
                      gifName: "telugu_ya_yanakam", audioName: "te_య"),
                .init(symbol: "ర", exampleWord: "రాజు", exampleEmoji: "👑",
                      gifName: "telugu_ra_raju", audioName: "te_ర"),
                .init(symbol: "ల", exampleWord: "లేడి", exampleEmoji: "🦌",
                      gifName: "telugu_la_ledi", audioName: "te_ల"),
                .init(symbol: "వ", exampleWord: "వానరం", exampleEmoji: "🐒",
                      gifName: "telugu_va_vanaram", audioName: "te_వ"),
                .init(symbol: "శ", exampleWord: "శంఖం", exampleEmoji: "🐚",
                      gifName: "telugu_sha_shankam", audioName: "te_శ"),
                .init(symbol: "ష", exampleWord: "షట్కోణం", exampleEmoji: "⬡",
                      gifName: "telugu_sha_shatkonam", audioName: "te_ష"),
                .init(symbol: "స", exampleWord: "సింహం", exampleEmoji: "🦁",
                      gifName: "telugu_sa_simham", audioName: "te_స"),
                .init(symbol: "హ", exampleWord: "హంస", exampleEmoji: "🦢",
                      gifName: "telugu_ha_hamsa", audioName: "te_హ"),
                .init(symbol: "ళ", exampleWord: "ళకుమారం", exampleEmoji: "🌟",
                      gifName: "telugu_la_lakumaram", audioName: "te_ళ"),
                .init(symbol: "క్ష", exampleWord: "క్షీరం", exampleEmoji: "🥛",
                      gifName: "telugu_ksha_ksheeram", audioName: "te_క్ష"),
                .init(symbol: "ఱ", exampleWord: "ఱెక్క", exampleEmoji: "🪶",
                      gifName: "telugu_ra_rekka", audioName: "te_ఱ")
            ]
            
        case .hindi:
            return [
                // Vowels (Swar)
                .init(symbol: "अ", exampleWord: "अनार", exampleEmoji: "🍎",
                      gifName: "hindi_a_anaar", audioName: "hi_अ"),
                .init(symbol: "आ", exampleWord: "आम", exampleEmoji: "🥭",
                      gifName: "hindi_aa_aam", audioName: "hi_आ"),
                .init(symbol: "इ", exampleWord: "इमली", exampleEmoji: "🌿",
                      gifName: "hindi_i_imli", audioName: "hi_इ"),
                .init(symbol: "ई", exampleWord: "ईख", exampleEmoji: "🎋",
                      gifName: "hindi_ee_eekh", audioName: "hi_ई"),
                .init(symbol: "उ", exampleWord: "उल्लू", exampleEmoji: "🦉",
                      gifName: "hindi_u_ulloo", audioName: "hi_उ"),
                .init(symbol: "ऊ", exampleWord: "ऊंट", exampleEmoji: "🐫",
                      gifName: "hindi_oo_oonth", audioName: "hi_ऊ"),
                .init(symbol: "ऋ", exampleWord: "ऋषि", exampleEmoji: "🧘",
                      gifName: "hindi_ri_rishi", audioName: "hi_ऋ"),
                .init(symbol: "ए", exampleWord: "एक", exampleEmoji: "1️⃣",
                      gifName: "hindi_e_ek", audioName: "hi_ए"),
                .init(symbol: "ऐ", exampleWord: "ऐनक", exampleEmoji: "👓",
                      gifName: "hindi_ai_ainak", audioName: "hi_ऐ"),
                .init(symbol: "ओ", exampleWord: "ओखली", exampleEmoji: "🍚",
                      gifName: "hindi_o_okhli", audioName: "hi_ओ"),
                .init(symbol: "औ", exampleWord: "औरत", exampleEmoji: "👩",
                      gifName: "hindi_au_aurat", audioName: "hi_औ"),
                .init(symbol: "अं", exampleWord: "अंगूर", exampleEmoji: "🍇",
                      gifName: "hindi_an_angoor", audioName: "hi_अं"),
                .init(symbol: "अः", exampleWord: "अःकार", exampleEmoji: "😤",
                      gifName: "hindi_ah_ahakaar", audioName: "hi_अः"),
                
                // Consonants (Vyanjan)
                .init(symbol: "क", exampleWord: "कबूतर", exampleEmoji: "🕊️",
                      gifName: "hindi_ka_kabutar", audioName: "hi_क"),
                .init(symbol: "ख", exampleWord: "खरगोश", exampleEmoji: "🐰",
                      gifName: "hindi_kha_khargosh", audioName: "hi_ख"),
                .init(symbol: "ग", exampleWord: "गाय", exampleEmoji: "🐄",
                      gifName: "hindi_ga_gay", audioName: "hi_ग"),
                .init(symbol: "घ", exampleWord: "घड़ी", exampleEmoji: "⌚",
                      gifName: "hindi_gha_ghadi", audioName: "hi_घ"),
                .init(symbol: "ङ", exampleWord: "ङकार", exampleEmoji: "🔤",
                      gifName: "hindi_nga_ngakar", audioName: "hi_ङ"),
                .init(symbol: "च", exampleWord: "चम्मच", exampleEmoji: "🥄",
                      gifName: "hindi_cha_chammach", audioName: "hi_च"),
                .init(symbol: "छ", exampleWord: "छाता", exampleEmoji: "☂️",
                      gifName: "hindi_chha_chhata", audioName: "hi_छ"),
                .init(symbol: "ज", exampleWord: "जहाज", exampleEmoji: "✈️",
                      gifName: "hindi_ja_jahaj", audioName: "hi_ज"),
                .init(symbol: "झ", exampleWord: "झंडा", exampleEmoji: "🚩",
                      gifName: "hindi_jha_jhanda", audioName: "hi_झ"),
                .init(symbol: "ञ", exampleWord: "ञकार", exampleEmoji: "🔤",
                      gifName: "hindi_nya_nyakar", audioName: "hi_ञ"),
                .init(symbol: "ट", exampleWord: "टमाटर", exampleEmoji: "🍅",
                      gifName: "hindi_ta_tamatar", audioName: "hi_ट"),
                .init(symbol: "ठ", exampleWord: "ठंडाई", exampleEmoji: "🥤",
                      gifName: "hindi_tha_thandai", audioName: "hi_ठ"),
                .init(symbol: "ड", exampleWord: "डमरू", exampleEmoji: "🥁",
                      gifName: "hindi_da_damru", audioName: "hi_ड"),
                .init(symbol: "ढ", exampleWord: "ढोल", exampleEmoji: "🥁",
                      gifName: "hindi_dha_dhol", audioName: "hi_ढ"),
                .init(symbol: "ण", exampleWord: "णकार", exampleEmoji: "🔤",
                      gifName: "hindi_na_nakar", audioName: "hi_ण"),
                .init(symbol: "त", exampleWord: "तोता", exampleEmoji: "🦜",
                      gifName: "hindi_ta_tota", audioName: "hi_त"),
                .init(symbol: "थ", exampleWord: "थैला", exampleEmoji: "👜",
                      gifName: "hindi_tha_thaila", audioName: "hi_थ"),
                .init(symbol: "द", exampleWord: "दवाई", exampleEmoji: "💊",
                      gifName: "hindi_da_dawai", audioName: "hi_द"),
                .init(symbol: "ध", exampleWord: "धनुष", exampleEmoji: "🏹",
                      gifName: "hindi_dha_dhanush", audioName: "hi_ध"),
                .init(symbol: "न", exampleWord: "नल", exampleEmoji: "🚰",
                      gifName: "hindi_na_nal", audioName: "hi_न"),
                .init(symbol: "प", exampleWord: "पंखा", exampleEmoji: "🪭",
                      gifName: "hindi_pa_pankha", audioName: "hi_प"),
                .init(symbol: "फ", exampleWord: "फूल", exampleEmoji: "🌸",
                      gifName: "hindi_pha_phool", audioName: "hi_फ"),
                .init(symbol: "ब", exampleWord: "बंदर", exampleEmoji: "🐒",
                      gifName: "hindi_ba_bandar", audioName: "hi_ब"),
                .init(symbol: "भ", exampleWord: "भालू", exampleEmoji: "🐻",
                      gifName: "hindi_bha_bhalu", audioName: "hi_भ"),
                .init(symbol: "म", exampleWord: "मछली", exampleEmoji: "🐟",
                      gifName: "hindi_ma_machli", audioName: "hi_म"),
                .init(symbol: "य", exampleWord: "यज्ञ", exampleEmoji: "🔥",
                      gifName: "hindi_ya_yagya", audioName: "hi_य"),
                .init(symbol: "र", exampleWord: "रस्सी", exampleEmoji: "🪢",
                      gifName: "hindi_ra_rassi", audioName: "hi_र"),
                .init(symbol: "ल", exampleWord: "लट्टू", exampleEmoji: "🪀",
                      gifName: "hindi_la_lattu", audioName: "hi_ल"),
                .init(symbol: "व", exampleWord: "वाघ", exampleEmoji: "🐯",
                      gifName: "hindi_va_wagh", audioName: "hi_व"),
                .init(symbol: "श", exampleWord: "शेर", exampleEmoji: "🦁",
                      gifName: "hindi_sha_sher", audioName: "hi_श"),
                .init(symbol: "ष", exampleWord: "षट्कोण", exampleEmoji: "⬡",
                      gifName: "hindi_sha_shatkon", audioName: "hi_ष"),
                .init(symbol: "स", exampleWord: "सांप", exampleEmoji: "🐍",
                      gifName: "hindi_sa_saanp", audioName: "hi_स"),
                .init(symbol: "ह", exampleWord: "हाथी", exampleEmoji: "🐘",
                      gifName: "hindi_ha_haathi", audioName: "hi_ह"),
                
                // Additional common conjuncts
                .init(symbol: "क्ष", exampleWord: "क्षत्रिय", exampleEmoji: "⚔️",
                      gifName: "hindi_ksha_kshatriya", audioName: "hi_क्ष"),
                .init(symbol: "त्र", exampleWord: "त्रिशूल", exampleEmoji: "🔱",
                      gifName: "hindi_tra_trishul", audioName: "hi_त्र"),
                .init(symbol: "ज्ञ", exampleWord: "ज्ञान", exampleEmoji: "📚",
                      gifName: "hindi_gya_gyan", audioName: "hi_ज्ञ")
            ]
        }
    }
    
    static func numbers(for lang: AppLanguage) -> [NumberItem] {
        switch lang {
        case .english:
            return (1...10).map { n in
                let words = ["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"]
                return .init(number: n, display: "\(n)", word: words[n-1],
                           gifName: "num_\(n)", audioName: "en_num_\(n)")
            }
            
        case .telugu:
            let digits = ["౧", "౨", "౩", "౪", "౫", "౬", "౭", "౮", "౯", "౧౦"]
            let words = ["ఒకటి", "రెండు", "మూడు", "నాలుగు", "ఐదు", "ఆరు", "ఏడు",
                        "ఎనిమిది", "తొమ్మిది", "పది"]
            return (1...10).map { n in
                .init(number: n, display: digits[n-1], word: words[n-1],
                     gifName: "te_num_\(n)", audioName: "te_num_\(n)")
            }
            
        case .hindi:
            let digits = ["१", "२", "३", "४", "५", "६", "७", "८", "९", "१०"]
            let words = ["एक", "दो", "तीन", "चार", "पाँच", "छह", "सात", "आठ", "नौ", "दस"]
            return (1...10).map { n in
                .init(number: n, display: digits[n-1], word: words[n-1],
                     gifName: "hi_num_\(n)", audioName: "hi_num_\(n)")
            }
        }
    }
}
